<a href="https://colab.research.google.com/github/Rajathshivraj/ML/blob/main/Completepandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas library
useful for Data processing and Data Analysis
pandas dataframe:
pandas dataframe is two dimenesional tabular data structure with labeled axes (rows and cols)

In [ ]:
#importing the boston house price data
from sklearn.datasets import fetch_california_housing
boston_dataset = fetch_california_housing()

In [ ]:
print(type(boston_dataset))

<class 'sklearn.utils._bunch.Bunch'>

In [ ]:
print(boston_dataset)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [ ]:
#pandas dataframe
import pandas as pd
boston_df=pd.DataFrame(boston_dataset.data,columns=boston_dataset.feature_names)

In [ ]:
boston_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
boston_df.shape

(20640, 8)

importing the data from a csv file to a pandas dataframe

In [ ]:
#csv file to pandas_df
diabetes_df = pd.read_csv('/content/diabetes.csv')

In [ ]:
type(diabetes_df)

pandas.core.frame.DataFrame

In [ ]:
type(boston_df)

pandas.core.frame.DataFrame

In [ ]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
diabetes_df.shape

(768, 9)

loading the data from excel file to a pandas data frame
pd.read_excel(filepath)

In [ ]:
#how to load all contents of dataframe to csv frame
boston_df.to_csv('boston.csv')

In [ ]:
#exporting ppandas df to excel file
boston_df.to_excel('boston.xlsx')

In [ ]:
#creating a df with random values
import numpy as np
random_df = pd.DataFrame(np.random.rand(20,10))

In [ ]:
random_df.head()

,0,1,2,3,4,5,6,7,8,9
0,0.373045,0.550913,0.613666,0.609301,0.323140,0.950303,0.418845,0.591397,0.283319,0.790251
1,0.010700,0.538715,0.594798,0.062409,0.929846,0.581488,0.074594,0.855268,0.377859,0.688937
2,0.349103,0.167394,0.933376,0.281507,0.108175,0.367877,0.925770,0.489677,0.310668,0.145920
3,0.540022,0.728616,0.424777,0.489312,0.686142,0.544907,0.491936,0.705461,0.671493,0.592471
4,0.452385,0.098225,0.257188,0.071525,0.802368,0.279631,0.300799,0.254013,0.700495,0.981456

In [ ]:
random_df.shape

(20, 10)

Inspecting a dataframe

In [ ]:
#finding the number of cols and rows

In [ ]:
boston_df.shape

(20640, 8)

In [ ]:
# last five rows
boston_df.tail()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
#information about the dataframe
boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [ ]:
#finding the no of missing values
boston_df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [ ]:
#counting the values based on the labels
boston_df.value_counts('HouseAge')

HouseAge
52.0    1273
36.0     862
35.0     824
16.0     771
17.0     698
34.0     689
26.0     619
33.0     615
18.0     570
25.0     566
32.0     565
37.0     537
15.0     512
19.0     502
27.0     488
24.0     478
30.0     476
28.0     471
20.0     465
29.0     461
31.0     458
23.0     448
21.0     446
14.0     412
22.0     399
38.0     394
39.0     369
42.0     368
44.0     356
43.0     353
40.0     304
13.0     302
41.0     296
45.0     294
10.0     264
11.0     254
46.0     245
5.0      244
12.0     238
8.0      206
9.0      205
47.0     198
4.0      191
48.0     177
7.0      175
6.0      160
50.0     136
49.0     134
3.0       62
2.0       58
51.0      48
1.0        4
Name: count, dtype: int64

In [ ]:
#group the values based on their mean
boston_df.groupby('HouseAge').mean()

,MedInc,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
HouseAge,,,,,,,
1.0,4.003400,9.088091,1.552106,328.500000,3.244088,36.205000,-119.457500
2.0,5.167766,7.649087,1.273514,2083.051724,2.747802,35.494483,-119.121379
3.0,5.460258,6.851805,1.192486,3001.774194,2.734708,35.284516,-118.936452
4.0,5.180673,6.112610,1.116190,2813.162304,2.786138,34.966963,-118.814293
5.0,4.697636,5.963211,1.128014,2471.381148,3.279108,35.234262,-118.918033
6.0,4.383393,5.832246,1.105839,2165.637500,2.886158,35.233125,-118.994313
7.0,4.464457,6.236576,1.145118,2613.080000,2.936948,35.544286,-119.111486
8.0,4.459338,6.280481,1.175100,2018.354369,3.360742,35.743835,-119.320243
9.0,4.316425,6.014117,1.144547,1886.975610,2.899606,35.683366,-119.305415
10.0,4.050508,6.047608,1.195510,1712.924242,2.852738,35.914621,-119.400492
11.0,3.932593,6.288396,1.245155,1989.905512,2.932461,35.896063,-119.484803
12.0,3.988412,5.766874,1.122970,2129.613445,2.902287,35.731891,-119.346261
13.0,4.150874,6.225630,1.199163,1776.347682,2.875146,35.817417,-119.380762
14.0,4.115541,6.101843,1.175591,1857.140777,2.871762,35.975267,-119.548981
15.0,4.062305,5.942703,1.142600,1622.308594,2.824927,35.900430,-119.497109
16.0,4.293998,6.004060,1.131531,1483.556420,2.916834,35.732257,-119.557588
17.0,3.935827,5.879533,1.168132,1605.848138,2.819008,35.965043,-119.630645
18.0,3.977344,5.708517,1.124104,1608.664912,2.895784,35.944965,-119.672000
19.0,3.760389,5.632239,1.138902,1619.286853,2.860078,35.826892,-119.528127
20.0,3.778618,5.466440,1.112190,1545.584946,2.863815,36.143140,-119.891828
21.0,3.852120,5.536552,1.110378,1657.793722,2.876149,35.779641,-119.629036
22.0,3.922650,5.661284,1.130028,1736.686717,2.950788,35.824912,-119.663033
23.0,3.949525,5.584120,1.113509,1554.285714,2.935799,35.732299,-119.625000
24.0,3.911442,5.404322,1.090811,1610.000000,2.910523,35.410502,-119.348766
25.0,4.119936,5.542334,1.102046,1539.491166,2.876420,35.503728,-119.436696
26.0,4.076914,5.547365,1.072149,1437.591276,3.051294,35.506672,-119.494330
27.0,3.853651,5.345399,1.101355,1412.657787,2.893323,35.620307,-119.629488
28.0,3.752313,5.213263,1.086258,1443.577495,2.967666,35.555669,-119.549512
29.0,3.580305,5.215443,1.088691,1454.225597,2.991591,35.503362,-119.448243
30.0,3.587635,5.086314,1.082066,1413.836134,3.049689,35.446513,-119.458571
31.0,3.607926,4.962658,1.059985,1390.796943,3.035894,35.370197,-119.405087
32.0,3.778895,5.174086,1.060452,1364.886726,3.087233,35.475044,-119.453912
33.0,3.832625,5.443103,1.101136,1304.369106,3.112717,35.385740,-119.377935
34.0,3.984903,5.463408,1.099826,1233.134978,3.049085,35.164470,-119.200334
35.0,3.913107,5.201818,1.039142,1204.427184,3.147272,35.170728,-119.255316
36.0,3.935958,5.252212,1.042671,1093.349188,3.786374,35.172459,-119.273179
37.0,3.747540,5.099511,1.054990,1080.089385,3.035523,35.338454,-119.444115
38.0,3.446261,4.991169,1.065688,1100.913706,3.036302,35.350482,-119.363173
39.0,3.437686,4.872036,1.053098,1160.252033,3.008323,35.514824,-119.632005
40.0,3.456350,4.891881,1.053887,1094.674342,2.982353,35.440493,-119.557993
41.0,3.170057,4.713015,1.053664,1040.043919,3.100736,35.344966,-119.429291
42.0,3.431315,4.764322,1.043766,1134.913043,3.056921,35.346005,-119.480543
43.0,3.211136,4.759272,1.049097,1064.963173,2.950987,35.556176,-119.668102
44.0,3.503119,5.057172,1.067361,1031.109551,2.889532,35.326910,-119.516180
45.0,3.665441,4.976640,1.037650,1035.323129,7.111575,35.494252,-119.669932
46.0,3.398138,4.902913,1.046044,1051.808163,4.849529,35.652939,-119.811551
47.0,3.290915,4.916969,1.062047,1060.015152,2.936009,35.777576,-119.927576
48.0,3.473160,5.085865,1.067385,970.926554,2.782648,35.715254,-119.816667
49.0,3.550495,4.966750,1.043057,989.194030,2.721458,36.015075,-120.275672
50.0,3.444289,4.942963,1.072900,998.977941,2.777761,35.987279,-120.123603
51.0,3.423648,4.890285,1.045443,941.312500,2.548105,36.359167,-120.489167
52.0,3.889047,5.100120,1.066982,934.271013,2.840404,36.605161,-120.885915

statistical measures

In [ ]:
#count or no of values in each df
boston_df.count()

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
dtype: int64

In [ ]:
# mean value column wise
boston_df.mean()

MedInc           3.870671
HouseAge        28.639486
AveRooms         5.429000
AveBedrms        1.096675
Population    1425.476744
AveOccup         3.070655
Latitude        35.631861
Longitude     -119.569704
dtype: float64

In [ ]:
boston_df.std()

MedInc           1.899822
HouseAge        12.585558
AveRooms         2.474173
AveBedrms        0.473911
Population    1132.462122
AveOccup        10.386050
Latitude         2.135952
Longitude        2.003532
dtype: float64

In [ ]:
#minimum value
boston_df.min()

MedInc          0.499900
HouseAge        1.000000
AveRooms        0.846154
AveBedrms       0.333333
Population      3.000000
AveOccup        0.692308
Latitude       32.540000
Longitude    -124.350000
dtype: float64

In [ ]:
#maximum value
boston_df.max()

MedInc           15.000100
HouseAge         52.000000
AveRooms        141.909091
AveBedrms        34.066667
Population    35682.000000
AveOccup       1243.333333
Latitude         41.950000
Longitude      -114.310000
dtype: float64

In [ ]:
#all statistical measures in one go
boston_df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

manipulating a dataframe

In [ ]:
# adding a coloumn to a dataframe
boston_df['Price'] = boston_dataset.target

In [ ]:
# removing a row
boston_df.drop(index=1,axis=0)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [ ]:
#remove col
boston_df.drop(columns='Price',axis=1)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
#locating a row using index value
boston_df.iloc[2]

MedInc          7.257400
HouseAge       52.000000
AveRooms        8.288136
AveBedrms       1.073446
Population    496.000000
AveOccup        2.802260
Latitude       37.850000
Longitude    -122.240000
Price           3.521000
Name: 2, dtype: float64

In [ ]:
#locating a particular col
boston_df.iloc[:,0]#first colof df

0        8.3252
1        8.3014
2        7.2574
3        5.6431
4        3.8462
          ...
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: MedInc, Length: 20640, dtype: float64

In [ ]:
 #correlation:
 #positive and negative correlation
 boston_df.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.688075
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,0.105623
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.151948
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.046701
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,-0.024650
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,-0.023737
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.144160
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.045967
Price,0.688075,0.105623,0.151948,-0.046701,-0.024650,-0.023737,-0.144160,-0.045967,1.000000